---
- name: Run a docker image
  hosts: localhost
  #become: yes
  tasks:
  - name: "Building docker image"
    command: docker build -t assignment -f /var/lib/jenkins/workspace/Dockerfile --build-arg abc={{input}} .
  - name: "printing env vars"
    command: docker run assignment printenv
